### ISSUE TITLE
attribute inspector not showing fincode properties

### ISSUE THREAD

**Issue by rrfunde** [fincode-byGMO/fincode-sdk-ios#2]
<img width="1544" alt="Screenshot 2023-02-24 at 14 01 49" src="https://user-images.githubusercontent.com/8462776/221096366-87908e19-fe93-4605-9606-3e24370e0aa4.png">

**Comment by fincode-developer** [comment]
@rrfunde 
When you install the FincodeSDK project using the "FincodeSDKプロジェクトの組み込み" method, the Attribute inspector will be displayed. 

On the other hand, if you install the FincodeSDK.xcframework using the "FincodeSDK.xcframeworkの組み込み" method, you can choose whether or not to display it by adding certain Identity inspector properties.

| Key Path | Type | Value |
| :-- | :-- | :-: |
| headingHidden  | Boolean | ✅ |
| dynamicLogDisplay  | Boolean | ✅ |
| methodHidden | Boolean | ✅ |
| payTimesHidden | Boolean | ✅ |
| holderNameHidden  | Boolean | ✅ |

![Xcode config page screenshot](https://user-images.githubusercontent.com/103908743/223365727-75f11202-8c94-46fd-ac09-b79033127275.png)

I hope this helps! Let me know if you have any other questions.

**Comment by rrfunde** [comment]
thank you, I got it now.
